### PR TITLE
Avatar & badge

### PR DESCRIPTION
**Pull request by amartya-rs**
Feature update: Build avatar and badge components

Screenshot (363)
.

### CODE REVIEW

**Review by sanu29 — APPROVED** [review]
All good 👍 
Just some extra spaces could be removed. Naming conventions could be better like they should be understandable 
eg: alert-l could be alert-lg

But still great work

**Comment by amartya-rs** [comment]
> All good 👍 Just some extra spaces could be removed. Naming conventions could be better like they should be understandable eg: alert-l could be alert-lg
> 
> But still great work

Thanks Saniya for feedback. I have updated the names and reduced some spacing. You can find them in the latest commit.

**Review by zoef-yt — APPROVED** [review]
looks good. Good to merge.

**Review by archit7448 — APPROVED** [review]
Good to merge

**Review by tonymike99 — APPROVED** [review]
Good to go!

**Pull request merged**
